---
- name: Set cache folder permissions
  shell: >
    APACHEUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data' | grep -v root | head -1 | cut -d ' ' -f1` &&
    setfacl -R -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_current_source_dir }}/app/cache {{ symfony_current_source_dir }}/app/logs &&
    setfacl -dR -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_current_source_dir }}/app/cache {{ symfony_current_source_dir }}/app/logs
  tags:
    - cache
    
- name: Remove cache dir manually.
  file: state=absent path={{symfony_current_source_dir}}/app/cache/{{symfony_project_env}}
  when: symfony_project_enable_cache_warmup == True
  tags:
    - cache

- name: Warmup sf cache.
  shell: cd {{symfony_current_source_dir}} && export SYMFONY_ENV={{symfony_project_env}}; {{symfony_project_php_path}} {{symfony_project_php_options}} {{symfony_console}} {{symfony_project_cache_command}} {{symfony_project_console_opts}}
  when: symfony_project_enable_cache_warmup == True
  tags:
    - cache