---
# tasks file for symfony2
- include: facts.yml

- name: Create/prepare necessary directories for release and shared data.
  file: state=directory path={{item.path}}
  with_items:
    - { path: "{{symfony_current_release_dir}}" }
    - { path: "{{symfony_shared_dir}}" }
    - { path: "{{symfony_shared_dir}}/app/config" }
    - { path: "{{symfony_shared_dir}}/app/logs" }
    - { path: "{{symfony_shared_dir}}/web/uploads" }

#- name: Create/prepare additionaly configured web folders
#  file: state=directory path={{item.path}}

- name: Pull sources from the repository.
  git: repo={{symfony_project_repo}} dest={{symfony_current_release_dir}} version={{symfony_project_branch}} accept_hostkey=yes depth={{symfony_project_git_clone_depth}}

# read project's composer.json and store output
- shell: cat {{symfony_current_release_dir}}/composer.json
  register: composer_content

- include: "{{ symfony_project_post_folder_creation_tasks | default('empty.yml') }}"

# will be replaced with symlink
- name: Ensure logs directory is not present.
  file: state=absent path="{{symfony_current_release_dir}}/app/logs"

- name: Create symlinks to shared directories.
  file: state=link src="{{symfony_shared_dir}}{{item.src}}" path="{{symfony_current_release_dir}}{{item.path}}"
  with_items:
    - { src: "/app/logs", path: "/app/logs" }
    - { src: "/web/uploads", path: "/web/uploads" }

- include: config.yml

- include: composer.yml

- include: "{{ symfony_project_pre_cache_warmup_tasks | default('empty.yml') }}"

- include: cache.yml

- include: assets.yml

- include: migrations.yml

- name: create release file
  copy: content="{{symfony_current_release}}" dest="{{symfony_current_release_dir}}/RELEASE" mode=644

- include: "{{ symfony_project_pre_live_switch_tasks | default('empty.yml') }}"

- name: Create symlink for release.
  file: state=link src="{{symfony_current_release_dir}}" path="{{symfony_project_root}}/current"

- include: "{{ symfony_project_post_live_switch_tasks | default('empty.yml') }}"

- include: clean_releases.yml